name: CI-Pipeline

on: push

jobs:
  build-and-test:
    name: Build & Test Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ahmadissa/docker-react -f Dockerfile.dev .

      - name: Run Tests
        run: |
          docker run -e CI=true ahmadissa/docker-react npm run test
